# configs/seg_cityscape_singletask.yaml

data:
  type: "cityscapes"
  dataset_path: "../mtl_dataset/cityscapes" # 请确保路径与您的环境一致
  batch_size: 8       # Cityscapes 图片较大，如果显存不足请改为 4
  num_workers: 4
  img_size: [384, 384]
  pin_memory: True

model:
  type: "single_task"    # 指定 SingleTaskModel
  active_task: "seg"     # ★ 激活分割
  encoder_name: "vit_b_16"
  pretrained: True
  num_scene_classes: 1   # Cityscapes 只有一个大类，设为 1

training:
  seed: 42
  epochs: 100            # Cityscapes 建议多训一些 (100 vs NYUv2的50)
  optimizer: "AdamW"
  learning_rate: 0.0001
  weight_decay: 0.01
  lr_scheduler:
    type: cosine
    warmup_epochs: 3
    min_lr_factor: 0.1

losses:
  lambda_seg: 10.0       # 只开启分割 Loss
  lambda_depth: 0.0
  lambda_scene: 0.0